apiVersion : apps/v1
kind: Deployment
metadata:
  name: tomcatapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata:
      labels:
        app: tomcatapp 
    spec:
      containers:
        - name: tomcatapp 
          image: tomcatcontainerregistry.azurecr.io/tomcatapp
          ports:
          - containerPort: 8080