apiVersion : apps/v1
kind: Deployment
metadata:
  name: begimzhanakhmatovatomcatapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: begimzhanakhmatovatomcatapp
  template:
    metadata:
      labels:
        app: begimzhanakhmatovatomcatapp 
    spec:
      containers:
        - name: begimzhanakhmatovatomcatapp 
          image: tomcatcontainerregistry.azurecr.io/begimzhanakhmatovatomcatapp
          ports:
          - containerPort: 8080